add: manage/mamberAuthorizeWindow component
HICC-WebsiteProduction/HICC-Website-Production-Frontend pull request #7
Opened 2023-02-16 10:13 UTC by Guardian-demoN

# 멤버 승인 컴포넌트 및 관리 페이지 통합
## 주요 변경 내용
- `MemberAuthorizeWindow.js` 페이지 및 `MemberAuthorizeWindow` 컴포넌트를 생성했습니다.
- `Manage.js` 및 해당 컴포넌트에 연결했습니다.

## 참고 사항
- 본 branch는 `develop/manage` 브랜치의 서브 브랜치로 생성되었습니다.

## 남은 작업 내용
- 팝업 화면을 아직 만들지는 않았습니다. 이 부분에 대해서 협의가 필요합니다.
- react 및 css 컴포넌트에 대한 코드 리팩토링 작업을 예정하고 있습니다. 현재 react 컴포넌트와 html element를 혼용해 쓰는 것이 좋지 않다고 생각하기에 개선 예정입니다.

## 참고용 시연 사진
![image](https://user-images.githubusercontent.com/39708748/219334617-bcc71a33-83f2-419c-9489-5292c748e51f.png)

2023-02-16 11:50 UTC, jinhokim98 requested changes
CSS 순서 규칙 참고사이트 올립니다.
아래를 참고해서 순서를 바꿔주세요!
https://beautifulcss.com/archives/203

2023-02-16 11:50 UTC, jinhokim98 commented on frontend/src/components/MemberAuthorizeWindow.js
> +  width: 100%;
css 속성 순서규칙을 확실하게 할 예정입니다.
저도 순서규칙 틀린 것이 있다면 다시 고쳐서 pr올릴게요!

2023-02-16 14:23 UTC, Guardian-demoN commented on frontend/src/components/MemberAuthorizeWindow.js
> +  width: 100%;
작업 완료했습니다.

2023-02-16 14:24 UTC, Guardian-demoN commented
아래 1건에 대해 작업 완료했습니다.
- css code convention

2023-02-17 01:20 UTC, jinhokim98 approved these changes

2023-02-17 01:20 UTC, merged

2023-02-17 14:04 UTC, Guardian-demoN commented
branch 분리가 너무 많아질 것으로 예정되어 현재 최신 개발 진행중인 컴포넌트인 `cabinetRentWindow`만을 제외하고, 관리 페이지는 `develop/manage`로 통합하겠습니다.