add: umbrella rent window component and sliderbutton component
HICC-WebsiteProduction/HICC-Website-Production-Frontend pull request #8
Opened 2023-02-16 10:20 UTC by Guardian-demoN

# 우산 대여 컴포넌트 추가 및 관리 페이지 통합
## 주요 변경 내역
- 우산 대여 컴포넌트에 해당하는 `<UmbrellaRentWindow>` 컴포넌트 및 체크버튼에 UI 상응하는 `<SliderButton>`을 추가했으며, `manage.js`에 통합했습니다.

## 작업 예정 사항
- 역시 react component와 html element를 혼용하는 코드에 대한 작업을 수정할 예정입니다.
- `PR:develop/memberAuthorizeWindow`와 마찬가지로 팝업 컴포넌트에 대한 의논이 필요할 것으로 보입니다.

![image](https://user-images.githubusercontent.com/39708748/219336610-b85a6977-ab6c-4c4f-a52d-ed7d81a07c46.png)

2023-02-16 11:56 UTC, jinhokim98 requested changes
전체적으로 CSS 순서 규칙 바로잡아주시고, 혼용 이유 알려주세요!

2023-02-16 11:56 UTC, jinhokim98 commented on frontend/src/components/UmbrellaRentWindow.js
> +    height: ${pixelToRem(50)};
여기도 px와 pixelToRem을 혼용해서 사용하셨는데 사용 이유를 알려주세요!

2023-02-16 11:56 UTC, jinhokim98 commented on frontend/src/pages/Manage.js
> +  list-style: none;
CSS 순서규칙 참고해주세요!

2023-02-16 14:12 UTC, Guardian-demoN commented on frontend/src/components/UmbrellaRentWindow.js
> +    height: ${pixelToRem(50)};
* px와 pixelToRem 혼용이 아닌 % 사용으로, 리뷰어와 대화 후 대화 종료합니다.

2023-02-16 14:14 UTC, Guardian-demoN commented on frontend/src/pages/Manage.js
> +  list-style: none;
해당 파일은 develop/manage 브랜치 수정 사항에 반영했습니다. 해당 PR이 승인되면 해당 브랜치에서 수정한 본 파일 역시 수정될 예정입니다.

2023-02-16 14:24 UTC, Guardian-demoN commented
아래 2건에 대해 작업 완료했습니다.
- css code convention
- resolved warning

2023-02-17 01:21 UTC, jinhokim98 approved these changes

2023-02-17 01:23 UTC, merged

2023-02-17 14:04 UTC, Guardian-demoN commented
branch 분리가 너무 많아질 것으로 예상하여 현재 최신 개발 진행중인 컴포넌트인 cabinetRentWindow만을 제외하고, 관리 페이지는 develop/manage로 통합하겠습니다.